export const PARTS = [
  {
    id: 'Foundation',
    pos: [0, 0, 0],
    exp: [0, -1, 0],
    size: [4, 0.5, 4],
    sequence: 1,
    wire: false,
    variants: [
      {
        label: 'Type A – Pre-cast Concrete',
        color: '#95a5a6',
        meta: 'Pre-cast Concrete Slab (Type A)',
        weight_kg: 4200,
        unit_cost_usd: 8500,
      },
      {
        label: 'Type B – Post-tensioned Slab',
        color: '#7f8c8d',
        meta: 'Post-tensioned Concrete Slab – High Load',
        weight_kg: 5100,
        unit_cost_usd: 11200,
      },
      {
        label: 'Type C – Hollow-core Plank',
        color: '#bdc3c7',
        meta: 'Hollow-core Pre-stressed Plank – Lightweight',
        weight_kg: 2800,
        unit_cost_usd: 6400,
      },
    ],
  },
  {
    id: 'Structure',
    pos: [0, 1.25, 0],
    exp: [0, 1.25, 0],
    size: [3.8, 2, 3.8],
    sequence: 2,
    wire: true,
    variants: [
      {
        label: 'Steel Frame – Smart BIM',
        color: '#34495e',
        meta: 'Steel Frame – Smart BIM Standard',
        weight_kg: 3600,
        unit_cost_usd: 22000,
      },
      {
        label: 'Heavy Steel Frame',
        color: '#1c2833',
        meta: 'Heavy Structural Steel – Column & Beam',
        weight_kg: 5200,
        unit_cost_usd: 31000,
      },
      {
        label: 'Timber Frame (CLT)',
        color: '#a0522d',
        meta: 'Cross-laminated Timber Frame – Low Carbon',
        weight_kg: 1800,
        unit_cost_usd: 18500,
      },
    ],
  },
  {
    id: 'Bathroom Pod',
    pos: [0.8, 1.25, 0.8],
    exp: [2.5, 1.25, 2.5],
    size: [1.5, 1.8, 1.5],
    sequence: 3,
    variants: [
      {
        label: 'Pod Type 01 – Standard',
        color: '#e67e22',
        meta: 'Off-site Fabricated Unit 01 – Standard',
        weight_kg: 2100,
        unit_cost_usd: 14000,
      },
      {
        label: 'Pod Type 02 – Accessible',
        color: '#d35400',
        meta: 'Off-site Fabricated Unit 02 – ADA Accessible',
        weight_kg: 2400,
        unit_cost_usd: 17500,
      },
      {
        label: 'Pod Type 03 – Compact',
        color: '#f39c12',
        meta: 'Off-site Fabricated Unit 03 – Compact Module',
        weight_kg: 1600,
        unit_cost_usd: 10800,
      },
    ],
  },
  {
    id: 'Cladding',
    pos: [-1.9, 1.25, 0],
    exp: [-3.5, 1.25, 0],
    size: [0.1, 2.2, 3.8],
    sequence: 4,
    variants: [
      {
        label: 'Insulated Glass Panel',
        color: '#27ae60',
        meta: 'Insulated Glass Panel – High Performance',
        weight_kg: 420,
        unit_cost_usd: 9200,
      },
      {
        label: 'Aluminum Composite Panel',
        color: '#16a085',
        meta: 'Aluminum Composite Rainscreen Panel',
        weight_kg: 310,
        unit_cost_usd: 6800,
      },
      {
        label: 'Brick Slip Façade',
        color: '#c0392b',
        meta: 'Pre-fabricated Brick Slip Cladding System',
        weight_kg: 680,
        unit_cost_usd: 11400,
      },
    ],
  },
  {
    id: 'Interface Layer',
    pos: [0, 2.5, 0],
    exp: [0, 4, 0],
    size: [4, 0.1, 4],
    sequence: 5,
    transparent: true,
    variants: [
      {
        label: 'Data & Utilities Slab',
        color: '#3498db',
        meta: 'Data & Utilities Distribution Layer',
        weight_kg: 180,
        unit_cost_usd: 4500,
      },
      {
        label: 'MEP Coordinated Slab',
        color: '#2980b9',
        meta: 'MEP Pre-coordinated Flat Slab Layer',
        weight_kg: 220,
        unit_cost_usd: 6200,
      },
      {
        label: 'Smart Services Layer',
        color: '#8e44ad',
        meta: 'Smart Building Services Integration Layer',
        weight_kg: 160,
        unit_cost_usd: 8900,
      },
    ],
  },
]
